;; -*- mode: eask; lexical-binding: t -*-

(package "smartparens"
         "1.11.0"
         "Automatic insertion, wrapping and paredit-like navigation with user defined pairs.")

(website-url "https://github.com/Fuco1/smartparens")
(keywords "abbrev" "convenience" "editing")

(package-file "smartparens.el")

(files "smartparens-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "28.1")
(depends-on "dash")

(development
 (depends-on "yasnippet")
 (depends-on "elsa")
 (depends-on "f")
 (depends-on "ert-runner")
 (depends-on "undercover")
 (depends-on "shut-up")
 (depends-on "racket-mode")
 (depends-on "scala-mode")
 (depends-on "rust-mode")
 (depends-on "swift-mode")
 (depends-on "auctex")
 (depends-on "clojure-mode")
 (depends-on "lua-mode")
 (depends-on "js2-mode")
 (depends-on "ess")
 (depends-on "tuareg")
 (depends-on "elixir-mode")
 (depends-on "haskell-mode")
 (depends-on "markdown-mode")
 (depends-on "hungry-delete")
 (depends-on "evil")
 (depends-on "crystal-mode")
 (depends-on "go-mode"))
